# Generated by Django 3.2 on 2021-04-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeping', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=3, null=True)),
            ],
        ),
    ]
