# Generated by Django 3.2 on 2021-04-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyform', '0002_auto_20210407_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyformmodel',
            name='createddate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyformmodel',
            name='sleeping',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=3, null=True),
        ),
    ]
