# Generated by Django 3.2 on 2021-04-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyform', '0003_auto_20210407_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyformmodel',
            options={'verbose_name_plural': 'Günlük Kayıt Formu'},
        ),
        migrations.AddField(
            model_name='dailyformmodel',
            name='drinkingwater',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=3, null=True),
        ),
    ]
