# Generated by Django 3.2 on 2021-04-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyform', '0004_auto_20210407_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyformmodel',
            name='steps',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=3, null=True),
        ),
    ]
