# Generated by Django 3.2 on 2021-04-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyform', '0008_savequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savequestion',
            name='message',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
