# Generated by Django 3.2 on 2021-04-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyform', '0009_alter_savequestion_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savequestion',
            options={'verbose_name_plural': 'Kullanıcının Eklenmesini İstediği Sorular'},
        ),
        migrations.RenameField(
            model_name='dailyformmodel',
            old_name='createddate',
            new_name='created_date',
        ),
    ]
