# Generated by Django 3.2 on 2021-04-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyform', '0014_dailyformmodel_eating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyformmodel',
            name='created_date',
            field=models.DateField(auto_now_add=True, max_length=10, null=True),
        ),
    ]
