# Generated by Django 3.2 on 2021-04-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyform', '0016_alter_dailyformmodel_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyformmodel',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
