# Generated by Django 3.2 on 2021-04-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyform', '0017_alter_dailyformmodel_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyformmodel',
            name='study',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=3, null=True),
        ),
    ]
