# Generated by Django 3.2 on 2021-04-12 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dailyform', '0019_likeapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeapp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_app', to=settings.AUTH_USER_MODEL),
        ),
    ]
