# Generated by Django 3.2 on 2021-04-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyform', '0020_alter_likeapp_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeApp',
        ),
    ]
